name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Install swift-format
      run: |
        brew install swift-format

    - name: Run linting
      run: make lint

    - name: Xcode setup
      shell: bash
      run: |
        sudo xcode-select -s /Applications/Xcode_16.3.app

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
